spring:
  config:
    activate:
      on-profile: maria

  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      idle-timeout: 180000 # 3*60*1000 = 3Min(유휴 상태 Connection 제거)
      max-lifetime: 900000 # 15*60*1000 = 15Min(최대 Connection 생존 시간)
      minimum-idle: 0 # 최소 Connection 수
      maximum-pool-size: 10 # 최대 Connection 수
      cache-prep-stmts: true # Prepared Statement 캐시 사용 여부
      prep-stmt-cache-size: 200 # Prepared Statement 캐시 사이즈
      prep-stmt-cache-sql-limit: 2048 # Prepared Statement 캐시 SQL 사이즈
      use-server-prep-stmts: true # 서버에서 Prepared Statement 사용 여부(서버 쿼리 최적화)
    url: jdbc:mariadb://localhost:3306/multi_dev?useSSL=false
    username: root
    password: 1234

# JPA Setting
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none #fixme
    defer-datasource-initialization: false #fixme
  sql:
    init:
      mode: never #fixme
# port
server:
  port: 8088